### PR TITLE
bump to 24.08

### PR DESCRIPTION
**Pull request by karman011**

### CODE REVIEW

**Comment by karman011** [comment]
https://github.com/flathub/com.obsproject.Studio.Plugin.GStreamerVaapi/issues/30
freedesktop SDK 24.08 dropped appstream-compose. I'll modify the manifest

**Comment by karman011** [comment]
image
I think it's working 
image
Here is the diff of metadata.
@TingPing Please have a look :).

**Comment by francoism90** [comment]
This seems to fix my issue #68 (Fedora Silverblue 41 beta).

**Comment by karman011** [comment]
> This seems to fix my issue #68 (Fedora Silverblue 41 beta).

Thanks for feedback!

**Comment by reenberg** [comment]
It seems like the build is no longer available.  Any chance to have this merged?  It sucks that this happens each time code bumps the SDK, and this then breaks for days.

**Comment by 0pendev** [comment]
bot, build

**Pull request merged**
